name: flutter2
description: "A Flutter Blog App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-82.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  fluttertoast: ^8.0.7
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.0.0
  image_picker: ^1.1.0
  path_provider: ^2.1.3
  quill_html_editor: ^2.2.8
  flutter_spinkit: ^5.2.1
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html: ^0.14.11
  flutter_cache_manager: ^3.3.2
  web_socket_channel: ^2.4.0
  stomp_dart_client: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/img/icons/
    - assets/img/posts/large/
    - assets/img/posts/small/
    - assets/img/stories/
    - assets/img/background/
    - assets/img/



